### ISSUE TITLE
Transitions / Lazy load

### ISSUE THREAD

**Issue by alejandronanez** [linasmnew/react-graceful-image#1]
Hey, thanks for creating this project!

Any plans on adding animations to transition from placeholder -> loaded image? or maybe adding lazy load?

Thanks!

**Comment by linasmnew** [comment]
Hi, 

Thanks for checking it out and those are some great ideas, I will look into it and get back to you.

**Comment by linasmnew** [comment]
Sorry for the delay, I've been sick for a couple of days.

I just [added](https://github.com/linasmnew/react-graceful-image/commit/2fb572dc366450e54a2a10b4083a5492c2d208c0) the "transition / fade-in" effect. As far as lazy loading goes I will look into that next and  publish the updates once I'm done.

**Comment by linasmnew** [comment]
It took a bit of time because of a problem with Safari producing unexpected behaviour but this has now been fixed. And a new version with fading in placeholder has now been published, update your package with npm to see this in action.

**Comment by alejandronanez** [comment]
That’s awesome! Thanks! Will try it later this week!

**Comment by linasmnew** [comment]
Just also added in lazy loading (on by default but can be turned off by passing in `noLazyLoad` prop)
