### ISSUE TITLE
Warning: Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by m9rco** [linasmnew/react-graceful-image#11]
index.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

**Comment by FabianHippmann** [comment]
https://github.com/linasmnew/react-graceful-image/pull/9 -> would solve this
