### ISSUE TITLE
android 5 The following will be compatibility problems

### ISSUE THREAD

**Issue by m9rco** [linasmnew/react-graceful-image#12]
![image](https://user-images.githubusercontent.com/18391791/57522852-d1283b80-7355-11e9-9216-80dcd2cf3824.png)

Will cause the entire webview blank，Didn't know what kind of way can solve it

**Comment by m9rco** [comment]
![image](https://user-images.githubusercontent.com/18391791/57522933-19475e00-7356-11e9-8bea-6839482aee40.png)

**Comment by m9rco** [comment]
Usually in circulation to create images on objects

**Comment by linasmnew** [comment]
Hey @m9rco, can you provide the error message if this is still an issue?

**Comment by m9rco** [comment]
I have not do the front-end programmers

**Comment by linasmnew** [comment]
Will close this for now due to a lack of information and no other reports of similar issues.
