### ISSUE TITLE
Did not work with next.js

### ISSUE THREAD

**Issue by coder054** [linasmnew/react-graceful-image#15]
It's say "document is not defined". I think because of the document is not available in server side environment

**Comment by OMGDuke** [comment]
You can use 'next/dyanmic' to ensure this component only loads on the client.

```import dynamic from 'next/dynamic';
const Image = dynamic(import('react-graceful-image'), { ssr: false });```

Then use the component like normal.

**Comment by linasmnew** [comment]
SSR has been fixed in `1.3.0`

**Comment by vendramini** [comment]
I tried to use with next.js now and it gives me the error:

![image](https://user-images.githubusercontent.com/510878/82588265-e80c8b00-9b70-11ea-8afc-22097f900245.png)

I'd to use dynamic imports like said above.

**Comment by vendramini** [comment]
I tried with next.js now and gives me the error: `window is not defined.`

Wrapping in a dynamic import, like said above, works.
