### ISSUE TITLE
How to add transition to placeholder [Feature Request]

### ISSUE THREAD

**Issue by sanishkr** [linasmnew/react-graceful-image#17]
Something similar to what [react shimmer](https://github.com/gokcan/react-shimmer) does.

How to add this animation:

  animation 1.5s loading-placeholder ease-in-out infinite
  -webkit-animation loading-placeholder 1.4s linear infinite;
  -moz-animation loading-placeholder 1.4s linear infinite;
  @keyframes loading-placeholder {
    0% {
      transform translateX(-100%);
    }
    100% {
      transform translateX(100%);
    }
  }

**Comment by mkgo** [comment]
@sanishkr Did you find a solution to this?
