### ISSUE TITLE
server rendering

### ISSUE THREAD

**Issue by philipheinser** [linasmnew/react-graceful-image#2]
throws an error `ReferenceError: document is not defined` when rendered on server.

**Comment by rackstar17** [comment]
Same is happening with me . 
I'm using nextjs SSR and using the component on client only , after componentDidMount but still showing the same error . 

Can you please help ?

**Comment by Lidofernandez** [comment]
Hi is there any progress on this ticket?

**Comment by Godofbrowser** [comment]
Hello @linasmnew Thanks for sharing your lib. I am currently using it in with nextjs for server side rendering and with a few modificatios, i was able to get it to work without errors.

I would do a pull request in my spare time to fix this along with other improvements.

**Comment by bedjiken** [comment]
@Godofbrowser, Im also using react-graceful-image in my SSR app one thing, document is not defined on server side.

I've waited for the component to be mounted in manually include it but still not working.

Would you please share your code where you get it to work without errors.

Thanks.

**Comment by vizFlux** [comment]
If you're using NextJS for your SSR app, I solved the issue with dynamic import like so:
`const Image = dynamic(() => import('react-graceful-image'));`

**Comment by itsanan** [comment]
**GatsbyJS**: "_window_" is not available during server side rendering.

Already tried several suggestion, still didn't work. 

1. Catch _window_ at componentDidMount()

`if (typeof window === 'undefined') {
        global.window = {};
      }`

2. Splitting the code

Suspected file that throwing the error : `./node_modules/react-graceful-image/lib/index.js`

Console : 
<img width="490" alt="Screenshot 2019-09-14 at 12 25 17 PM" src="https://user-images.githubusercontent.com/32235492/64903848-eb4e9d80-d6ea-11e9-87b5-a2ce7a6ccd5d.png">

**Comment by killmenot** [comment]
Have a solution but I need #14  to be merged first. If anyone interesting, you can see solution here https://github.com/Classuper/react-graceful-image/commit/4fc0136fbd3fe5ee78a12fbbdbcdfc58fd2d6d39

**Comment by tremblaysimon** [comment]
I've got the same error as @itsanan. Currently I'm using the workaround mentionned here for third-parties: https://www.gatsbyjs.org/docs/debugging-html-builds/ (and not rendering it if there is no windows defined...).

I think @killmenot have a good solution. Any chance to get an open PR for this soon (if #14 is merged as I understand)?

Thank you for all. If you need any help let us know @linasmnew.

**Comment by linasmnew** [comment]
Fixed in `1.3.0`
