### ISSUE TITLE
How to get the lastest version ?

### ISSUE THREAD

**Issue by GaelS** [linasmnew/react-graceful-image#5]
Hi !

Thanks for this very convenient library ! :+1: 

I was trying to get your latest update regarding the initial load of the images when they are in the viewport. As far as I understand however, your latest update is under the `react-graceful-image-fix` package on npm.

Have you planned to bump the version of the original package ? Just to know what to expect :)

Thank you !

**Comment by linasmnew** [comment]
Sorry, turns out while I fixed it couple weeks back, I forgot to compile the new changes before bumping... just did that now
