### ISSUE TITLE
Warning: Can't call setState (or forceUpdate) on an unmounted component.

### ISSUE THREAD

**Issue by markjaquith** [linasmnew/react-graceful-image#7]
This component outputs this, in some situations:

> Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

The problem is, like the error said, that asynchronous tasks aren't being canceled.

1. Call `this.throttledFunction.cancel()` at the top of `clearEventListeners()`.
2. Figure out a solution for the `setTimeout()` calls. Honestly, the easiest solution might be to set `this._isMounted = false` in the constructor, `this._isMounted = true` in `componentDidMount()`, and `this._isMounted = false` in `componentWillUnmount()`, and then create `setIsLoaded()` as a function that checks `this._isMounted` before calling `this.setState()`.

**Comment by markjaquith** [comment]
More info about the `this._isMounted` method here: https://reactjs.org/blog/2015/12/16/ismounted-antipattern.html

**Comment by hotyes** [comment]
got same error here

**Comment by m9rco** [comment]
emmm
