### ISSUE TITLE
Implement onLoad and onError

### ISSUE THREAD

**Issue by markjaquith** [linasmnew/react-graceful-image#8]
react-graceful-image should accept `onLoad` and `onError` props and fire them when appropriate. For `onError`, it shouldn't be on every `Image.onerror` of the underlying `Image` object, but only when it gives up after the allowed retries.

**Comment by arieaditya** [comment]
Agree with markjaquith, react-graceful-image should accept onError for fallback purpose especially when using webP images

**Comment by mkgo** [comment]
I also agree with this feature. I am looking for a way to show a loading progress bar while it's retrying and hide once the image is loaded.

Is there a different way to show a loading gif or just a set a different placeholder?

It would be great to have a placeholder={<MyCustomPlaceholder />}

**Comment by linasmnew** [comment]
Thanks for input, those are all really good ideas, will start addressing them 👍
